[package]
name = "wayrun-core"
version = "0.3.1"
edition = "2024"

[features]
default = ["compositor-niri"]
compositor-niri = []
compositor-hyprland = []

[dependencies]
anyhow = "1.0.102"
dirs = "6.0.0"
fasteval = "0.2.4"
gio = "0.22.9"
nucleo = "0.5.0"
notify = "8.2"
rusqlite = "0.38.0"
rust-i18n = { version = "1.2.2", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tempfile = "3.26.0"
tokio = { version = "1.50.0", features = ["rt-multi-thread", "macros", "process", "io-util", "io-std", "sync", "time"] }
toml = "1.1.2"
urlencoding = "2"
walkdir = "2.5.0"
freedesktop-desktop-entry = { version = "0.8", default-features = false }
minreq = { version = "3.0.0", default-features = false, features = ["https-native-tls", "json-using-serde", "urlencoding", "proxy"] }
