[[plugins]]
id = "calculator"
keyword = ""
enabled = true

[[plugins]]
id = "system-commands"
keyword = ""
enabled = true

[[plugins]]
id = "app-search"
keyword = ""

[[plugins]]
id = "runner"
keyword = "r"
enabled = true

[[plugins]]
id = "firefox-bookmarks"
keyword = "b"
script = "firefox.lua"
resident = true

[[plugins]]
id = "firefox-history"
keyword = "h"
script = "firefox.lua"
resident = true

[[plugins]]
id = "web-search"
keyword = "s"
script = "web.lua"
resident = true

[[plugins]]
id = "file-search"
keyword = "f"

[[plugins]]
id = "path-search"
keyword = "d"

[[plugins]]
id = "clipboard"
keyword = "c"

[[plugins]]
id = "window"
keyword = "w"
enabled = true
