[[plugins]]
id = "calculator"
keyword = ""
enabled = true

[[plugins]]
id = "system-commands"
keyword = ""
enabled = true

[[plugins]]
id = "app-search"
keyword = ""

[[plugins]]
id = "runner"
keyword = "r"
enabled = true

[[plugins]]
id = "file-search"
keyword = "f"

[[plugins]]
id = "path-search"
keyword = "d"

[[plugins]]
id = "clipboard"
keyword = "c"

[[plugins]]
id = "window"
keyword = "w"
enabled = true
